//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.21 at 04:00:48 PM BST
//


package eu.watchme.sm.models;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the eu.watchme.sm.models package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.watchme.sm.models
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KAF }
     *
     */
    public KAF createKAF() {
	return new KAF();
    }

    /**
     * Create an instance of {@link KAF.KafHeader }
     *
     */
    public KAF.KafHeader createKAFKafHeader() {
	return new KAF.KafHeader();
    }

    /**
     * Create an instance of {@link KAF.KafHeader.LinguisticProcessor }
     *
     */
    public KAF.KafHeader.LinguisticProcessor createKAFKafHeaderLinguisticProcessor() {
	return new KAF.KafHeader.LinguisticProcessor();
    }

    /**
     * Create an instance of {@link KAF.KafHeader.LinguisticProcessor.Lp }
     *
     */
    public KAF.KafHeader.LinguisticProcessor.Lp createKAFKafHeaderLinguisticProcessorLp() {
	return new KAF.KafHeader.LinguisticProcessor.Lp();
    }

    /**
     * Create an instance of {@link KAF.KafHeader.LinguisticProcessors }
     *
     */
    public KAF.KafHeader.LinguisticProcessors createKAFKafHeaderLinguisticProcessors() {
	return new KAF.KafHeader.LinguisticProcessors();
    }

    /**
     * Create an instance of {@link KAF.KafHeader.LinguisticProcessors.Lp }
     *
     */
    public KAF.KafHeader.LinguisticProcessors.Lp createKAFKafHeaderLinguisticProcessorsLp() {
	return new KAF.KafHeader.LinguisticProcessors.Lp();
    }

    /**
     * Create an instance of {@link KAF.Terms }
     *
     */
    public KAF.Terms createKAFTerms() {
	return new KAF.Terms();
    }

    /**
     * Create an instance of {@link KAF.Terms.Term }
     *
     */
    public KAF.Terms.Term createKAFTermsTerm() {
	return new KAF.Terms.Term();
    }

    /**
     * Create an instance of {@link KAF.Terms.Term.Span }
     *
     */
    public KAF.Terms.Term.Span createKAFTermsTermSpan() {
	return new KAF.Terms.Term.Span();
    }

    /**
     * Create an instance of {@link KAF.Terms.Term.Span.Target }
     *
     */
    public KAF.Terms.Term.Span.Target createKAFTermsTermSpanTarget() {
	return new KAF.Terms.Term.Span.Target();
    }

    /**
     * Create an instance of {@link KAF.Text }
     *
     */
    public KAF.Text createKAFText() {
	return new KAF.Text();
    }

    /**
     * Create an instance of {@link KAF.Text.Wf }
     *
     */
    public KAF.Text.Wf createKAFTextWf() {
	return new KAF.Text.Wf();
    }

}
