//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.21 at 04:00:48 PM BST
//


package eu.watchme.sm.models;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kafHeader">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="linguisticProcessors">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="lp" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                                     &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}String" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="linguisticProcessor">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="lp">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}String" />
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="text">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="wf" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}String" />
 *                           &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}String" />
 *                           &lt;attribute name="para" type="{http://www.w3.org/2001/XMLSchema}String" />
 *                           &lt;attribute name="sent" type="{http://www.w3.org/2001/XMLSchema}String" />
 *                           &lt;attribute name="wid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="terms">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="term" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="span">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="target">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="lemma" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="morphofeat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="pos" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="tid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"kafHeader",
		"text",
		"terms"
})
@XmlRootElement(name = "KAF")
public class KAF {

	/**
	 * <p>Java class for anonymous complex type.
	 *
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="linguisticProcessors">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="lp" maxOccurs="unbounded" minOccurs="0">
	 *                     &lt;complexType>
	 *                       &lt;simpleContent>
	 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
	 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                           &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
	 *                           &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}String" />
	 *                         &lt;/extension>
	 *                       &lt;/simpleContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="linguisticProcessor">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="lp">
	 *                     &lt;complexType>
	 *                       &lt;simpleContent>
	 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
	 *                           &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                           &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}String" />
	 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                         &lt;/extension>
	 *                       &lt;/simpleContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"linguisticProcessors",
			"linguisticProcessor"
	})
	public static class KafHeader {

		/**
		 * <p>Java class for anonymous complex type.
		 *
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="lp">
		 *           &lt;complexType>
		 *             &lt;simpleContent>
		 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
		 *                 &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}String" />
		 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *               &lt;/extension>
		 *             &lt;/simpleContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *       &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"lp"
		})
		public static class LinguisticProcessor {

			/**
			 * <p>Java class for anonymous complex type.
			 *
			 * <p>The following schema fragment specifies the expected content contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;simpleContent>
			 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
			 *       &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}String" />
			 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *     &lt;/extension>
			 *   &lt;/simpleContent>
			 * &lt;/complexType>
			 * </pre>
			 *
			 *
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = {
					"value"
			})
			public static class Lp {

				@XmlAttribute(name = "name")
				protected String name;
				@XmlAttribute(name = "timestamp")
				protected String timestamp;
				@XmlValue
				protected String value;
				@XmlAttribute(name = "version")
				protected String version;

				/**
				 * Gets the value of the name property.
				 *
				 * @return
				 *     possible object is
				 *     {@link String }
				 *
				 */
				public String getName() {
					return name;
				}

				/**
				 * Gets the value of the timestamp property.
				 *
				 * @return
				 *     possible object is
				 *     {@link String }
				 *
				 */
				public String getTimestamp() {
					return timestamp;
				}

				/**
				 * Gets the value of the value property.
				 *
				 * @return
				 *     possible object is
				 *     {@link String }
				 *
				 */
				public String getValue() {
					return value;
				}

				/**
				 * Gets the value of the version property.
				 *
				 * @return
				 *     possible object is
				 *     {@link String }
				 *
				 */
				public String getVersion() {
					return version;
				}

				/**
				 * Sets the value of the name property.
				 *
				 * @param value
				 *     allowed object is
				 *     {@link String }
				 *
				 */
				public void setName(String value) {
					this.name = value;
				}

				/**
				 * Sets the value of the timestamp property.
				 *
				 * @param value
				 *     allowed object is
				 *     {@link String }
				 *
				 */
				public void setTimestamp(String value) {
					this.timestamp = value;
				}

				/**
				 * Sets the value of the value property.
				 *
				 * @param value
				 *     allowed object is
				 *     {@link String }
				 *
				 */
				public void setValue(String value) {
					this.value = value;
				}

				/**
				 * Sets the value of the version property.
				 *
				 * @param value
				 *     allowed object is
				 *     {@link String }
				 *
				 */
				public void setVersion(String value) {
					this.version = value;
				}

			}
			@XmlAttribute(name = "layer")
			protected String layer;

			@XmlElement(required = true)
			protected KAF.KafHeader.LinguisticProcessor.Lp lp;

			/**
			 * Gets the value of the layer property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getLayer() {
				return layer;
			}

			/**
			 * Gets the value of the lp property.
			 *
			 * @return
			 *     possible object is
			 *     {@link KAF.KafHeader.LinguisticProcessor.Lp }
			 *
			 */
			public KAF.KafHeader.LinguisticProcessor.Lp getLp() {
				return lp;
			}

			/**
			 * Sets the value of the layer property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setLayer(String value) {
				this.layer = value;
			}


			/**
			 * Sets the value of the lp property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link KAF.KafHeader.LinguisticProcessor.Lp }
			 *
			 */
			public void setLp(KAF.KafHeader.LinguisticProcessor.Lp value) {
				this.lp = value;
			}

		}
		/**
		 * <p>Java class for anonymous complex type.
		 *
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="lp" maxOccurs="unbounded" minOccurs="0">
		 *           &lt;complexType>
		 *             &lt;simpleContent>
		 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
		 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *                 &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
		 *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}String" />
		 *               &lt;/extension>
		 *             &lt;/simpleContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *       &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"lp"
		})
		public static class LinguisticProcessors {

			/**
			 * <p>Java class for anonymous complex type.
			 *
			 * <p>The following schema fragment specifies the expected content contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;simpleContent>
			 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
			 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *       &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
			 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}String" />
			 *     &lt;/extension>
			 *   &lt;/simpleContent>
			 * &lt;/complexType>
			 * </pre>
			 *
			 *
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = {
					"value"
			})
			public static class Lp {

				@XmlAttribute(name = "name")
				protected String name;
				@XmlAttribute(name = "timestamp")
				@XmlSchemaType(name = "dateTime")
				protected XMLGregorianCalendar timestamp;
				@XmlValue
				protected String value;
				@XmlAttribute(name = "version")
				protected String version;

				/**
				 * Gets the value of the name property.
				 *
				 * @return
				 *     possible object is
				 *     {@link String }
				 *
				 */
				public String getName() {
					return name;
				}

				/**
				 * Gets the value of the timestamp property.
				 *
				 * @return
				 *     possible object is
				 *     {@link XMLGregorianCalendar }
				 *
				 */
				public XMLGregorianCalendar getTimestamp() {
					return timestamp;
				}

				/**
				 * Gets the value of the value property.
				 *
				 * @return
				 *     possible object is
				 *     {@link String }
				 *
				 */
				public String getValue() {
					return value;
				}

				/**
				 * Gets the value of the version property.
				 *
				 * @return
				 *     possible object is
				 *     {@link String }
				 *
				 */
				public String getVersion() {
					return version;
				}

				/**
				 * Sets the value of the name property.
				 *
				 * @param value
				 *     allowed object is
				 *     {@link String }
				 *
				 */
				public void setName(String value) {
					this.name = value;
				}

				/**
				 * Sets the value of the timestamp property.
				 *
				 * @param value
				 *     allowed object is
				 *     {@link XMLGregorianCalendar }
				 *
				 */
				public void setTimestamp(XMLGregorianCalendar value) {
					this.timestamp = value;
				}

				/**
				 * Sets the value of the value property.
				 *
				 * @param value
				 *     allowed object is
				 *     {@link String }
				 *
				 */
				public void setValue(String value) {
					this.value = value;
				}

				/**
				 * Sets the value of the version property.
				 *
				 * @param value
				 *     allowed object is
				 *     {@link String }
				 *
				 */
				public void setVersion(String value) {
					this.version = value;
				}

			}
			@XmlAttribute(name = "layer")
			protected String layer;

			protected List<KAF.KafHeader.LinguisticProcessors.Lp> lp;

			/**
			 * Gets the value of the layer property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getLayer() {
				return layer;
			}

			/**
			 * Gets the value of the lp property.
			 *
			 * <p>
			 * This accessor method returns a reference to the live list,
			 * not a snapshot. Therefore any modification you make to the
			 * returned list will be present inside the JAXB object.
			 * This is why there is not a <CODE>set</CODE> method for the lp property.
			 *
			 * <p>
			 * For example, to add a new item, do as follows:
			 * <pre>
			 *    getLp().add(newItem);
			 * </pre>
			 *
			 *
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link KAF.KafHeader.LinguisticProcessors.Lp }
			 *
			 *
			 */
			public List<KAF.KafHeader.LinguisticProcessors.Lp> getLp() {
				if (lp == null) {
					lp = new ArrayList<KAF.KafHeader.LinguisticProcessors.Lp>();
				}
				return this.lp;
			}


			/**
			 * Sets the value of the layer property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setLayer(String value) {
				this.layer = value;
			}

		}

		@XmlElement(required = true)
		protected KAF.KafHeader.LinguisticProcessor linguisticProcessor;

		@XmlElement(required = true)
		protected KAF.KafHeader.LinguisticProcessors linguisticProcessors;

		/**
		 * Gets the value of the linguisticProcessor property.
		 *
		 * @return
		 *     possible object is
		 *     {@link KAF.KafHeader.LinguisticProcessor }
		 *
		 */
		public KAF.KafHeader.LinguisticProcessor getLinguisticProcessor() {
			return linguisticProcessor;
		}

		/**
		 * Gets the value of the linguisticProcessors property.
		 *
		 * @return
		 *     possible object is
		 *     {@link KAF.KafHeader.LinguisticProcessors }
		 *
		 */
		public KAF.KafHeader.LinguisticProcessors getLinguisticProcessors() {
			return linguisticProcessors;
		}


		/**
		 * Sets the value of the linguisticProcessor property.
		 *
		 * @param value
		 *     allowed object is
		 *     {@link KAF.KafHeader.LinguisticProcessor }
		 *
		 */
		public void setLinguisticProcessor(KAF.KafHeader.LinguisticProcessor value) {
			this.linguisticProcessor = value;
		}


		/**
		 * Sets the value of the linguisticProcessors property.
		 *
		 * @param value
		 *     allowed object is
		 *     {@link KAF.KafHeader.LinguisticProcessors }
		 *
		 */
		public void setLinguisticProcessors(KAF.KafHeader.LinguisticProcessors value) {
			this.linguisticProcessors = value;
		}

	}
	/**
	 * <p>Java class for anonymous complex type.
	 *
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="term" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="span">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="target">
	 *                               &lt;complexType>
	 *                                 &lt;simpleContent>
	 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
	 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                                   &lt;/extension>
	 *                                 &lt;/simpleContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="lemma" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="morphofeat" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="pos" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="tid" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"term"
	})
	public static class Terms {

		/**
		 * <p>Java class for anonymous complex type.
		 *
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="span">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="target">
		 *                     &lt;complexType>
		 *                       &lt;simpleContent>
		 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
		 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *                         &lt;/extension>
		 *                       &lt;/simpleContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *       &lt;attribute name="lemma" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="morphofeat" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="pos" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="tid" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"span"
		})
		public static class Term {

			/**
			 * <p>Java class for anonymous complex type.
			 *
			 * <p>The following schema fragment specifies the expected content contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="target">
			 *           &lt;complexType>
			 *             &lt;simpleContent>
			 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
			 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *               &lt;/extension>
			 *             &lt;/simpleContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 *
			 *
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = {
					"target"
			})
			public static class Span {

				/**
				 * <p>Java class for anonymous complex type.
				 *
				 * <p>The following schema fragment specifies the expected content contained within this class.
				 *
				 * <pre>
				 * &lt;complexType>
				 *   &lt;simpleContent>
				 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
				 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
				 *     &lt;/extension>
				 *   &lt;/simpleContent>
				 * &lt;/complexType>
				 * </pre>
				 *
				 *
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = {
						"value"
				})
				public static class Target {

					@XmlAttribute(name = "id")
					protected String id;
					@XmlValue
					protected String value;

					/**
					 * Gets the value of the id property.
					 *
					 * @return
					 *     possible object is
					 *     {@link String }
					 *
					 */
					public String getId() {
						return id;
					}

					/**
					 * Gets the value of the value property.
					 *
					 * @return
					 *     possible object is
					 *     {@link String }
					 *
					 */
					public String getValue() {
						return value;
					}

					/**
					 * Sets the value of the id property.
					 *
					 * @param value
					 *     allowed object is
					 *     {@link String }
					 *
					 */
					public void setId(String value) {
						this.id = value;
					}

					/**
					 * Sets the value of the value property.
					 *
					 * @param value
					 *     allowed object is
					 *     {@link String }
					 *
					 */
					public void setValue(String value) {
						this.value = value;
					}

				}

				@XmlElement(required = true)
				protected KAF.Terms.Term.Span.Target target;

				/**
				 * Gets the value of the target property.
				 *
				 * @return
				 *     possible object is
				 *     {@link KAF.Terms.Term.Span.Target }
				 *
				 */
				public KAF.Terms.Term.Span.Target getTarget() {
					return target;
				}


				/**
				 * Sets the value of the target property.
				 *
				 * @param value
				 *     allowed object is
				 *     {@link KAF.Terms.Term.Span.Target }
				 *
				 */
				public void setTarget(KAF.Terms.Term.Span.Target value) {
					this.target = value;
				}

			}
			@XmlAttribute(name = "lemma")
			protected String lemma;
			@XmlAttribute(name = "morphofeat")
			protected String morphofeat;
			@XmlAttribute(name = "pos")
			protected String pos;
			@XmlElement(required = true)
			protected KAF.Terms.Term.Span span;
			@XmlAttribute(name = "tid")
			protected String tid;

			@XmlAttribute(name = "type")
			protected String type;

			/**
			 * Gets the value of the lemma property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getLemma() {
				return lemma;
			}

			/**
			 * Gets the value of the morphofeat property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getMorphofeat() {
				return morphofeat;
			}

			/**
			 * Gets the value of the pos property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getPos() {
				return pos;
			}

			/**
			 * Gets the value of the span property.
			 *
			 * @return
			 *     possible object is
			 *     {@link KAF.Terms.Term.Span }
			 *
			 */
			public KAF.Terms.Term.Span getSpan() {
				return span;
			}

			/**
			 * Gets the value of the tid property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getTid() {
				return tid;
			}

			/**
			 * Gets the value of the type property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getType() {
				return type;
			}

			/**
			 * Sets the value of the lemma property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setLemma(String value) {
				this.lemma = value;
			}

			/**
			 * Sets the value of the morphofeat property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setMorphofeat(String value) {
				this.morphofeat = value;
			}

			/**
			 * Sets the value of the pos property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setPos(String value) {
				this.pos = value;
			}

			/**
			 * Sets the value of the span property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link KAF.Terms.Term.Span }
			 *
			 */
			public void setSpan(KAF.Terms.Term.Span value) {
				this.span = value;
			}

			/**
			 * Sets the value of the tid property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setTid(String value) {
				this.tid = value;
			}


			/**
			 * Sets the value of the type property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setType(String value) {
				this.type = value;
			}

		}

		protected List<KAF.Terms.Term> term;


		/**
		 * Gets the value of the term property.
		 *
		 * <p>
		 * This accessor method returns a reference to the live list,
		 * not a snapshot. Therefore any modification you make to the
		 * returned list will be present inside the JAXB object.
		 * This is why there is not a <CODE>set</CODE> method for the term property.
		 *
		 * <p>
		 * For example, to add a new item, do as follows:
		 * <pre>
		 *    getTerm().add(newItem);
		 * </pre>
		 *
		 *
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link KAF.Terms.Term }
		 *
		 *
		 */
		public List<KAF.Terms.Term> getTerm() {
			if (term == null) {
				term = new ArrayList<KAF.Terms.Term>();
			}
			return this.term;
		}

	}
	/**
	 * <p>Java class for anonymous complex type.
	 *
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="wf" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
	 *                 &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}String" />
	 *                 &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}String" />
	 *                 &lt;attribute name="para" type="{http://www.w3.org/2001/XMLSchema}String" />
	 *                 &lt;attribute name="sent" type="{http://www.w3.org/2001/XMLSchema}String" />
	 *                 &lt;attribute name="wid" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"wf"
	})
	public static class Text {

		/**
		 * <p>Java class for anonymous complex type.
		 *
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
		 *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}String" />
		 *       &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}String" />
		 *       &lt;attribute name="para" type="{http://www.w3.org/2001/XMLSchema}String" />
		 *       &lt;attribute name="sent" type="{http://www.w3.org/2001/XMLSchema}String" />
		 *       &lt;attribute name="wid" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class Wf {

			@XmlAttribute(name = "length")
			protected String length;
			@XmlAttribute(name = "offset")
			protected String offset;
			@XmlAttribute(name = "para")
			protected String para;
			@XmlAttribute(name = "sent")
			protected String sent;
			@XmlValue
			protected String value;
			@XmlAttribute(name = "wid")
			protected String wid;

			/**
			 * Gets the value of the length property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getLength() {
				return length;
			}

			/**
			 * Gets the value of the offset property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getOffset() {
				return offset;
			}

			/**
			 * Gets the value of the para property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getPara() {
				return para;
			}

			/**
			 * Gets the value of the sent property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getSent() {
				return sent;
			}

			/**
			 * Gets the value of the value property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getValue() {
				return value;
			}

			/**
			 * Gets the value of the wid property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getWid() {
				return wid;
			}

			/**
			 * Sets the value of the length property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setLength(String value) {
				this.length = value;
			}

			/**
			 * Sets the value of the offset property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setOffset(String value) {
				this.offset = value;
			}

			/**
			 * Sets the value of the para property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setPara(String value) {
				this.para = value;
			}

			/**
			 * Sets the value of the sent property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setSent(String value) {
				this.sent = value;
			}

			/**
			 * Sets the value of the value property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setValue(String value) {
				this.value = value;
			}

			/**
			 * Sets the value of the wid property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setWid(String value) {
				this.wid = value;
			}

		}

		protected List<KAF.Text.Wf> wf;


		/**
		 * Gets the value of the wf property.
		 *
		 * <p>
		 * This accessor method returns a reference to the live list,
		 * not a snapshot. Therefore any modification you make to the
		 * returned list will be present inside the JAXB object.
		 * This is why there is not a <CODE>set</CODE> method for the wf property.
		 *
		 * <p>
		 * For example, to add a new item, do as follows:
		 * <pre>
		 *    getWf().add(newItem);
		 * </pre>
		 *
		 *
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link KAF.Text.Wf }
		 *
		 *
		 */
		public List<KAF.Text.Wf> getWf() {
			if (wf == null) {
				wf = new ArrayList<KAF.Text.Wf>();
			}
			return this.wf;
		}

	}
	@XmlElement(required = true)
	protected KAF.KafHeader kafHeader;
	@XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
	protected String lang;

	@XmlElement(required = true)
	protected KAF.Terms terms;

	@XmlElement(required = true)
	protected KAF.Text text;

	@XmlAttribute(name = "version")
	protected String version;

	/**
	 * Gets the value of the kafHeader property.
	 *
	 * @return
	 *     possible object is
	 *     {@link KAF.KafHeader }
	 *
	 */
	public KAF.KafHeader getKafHeader() {
		return kafHeader;
	}

	/**
	 * Gets the value of the lang property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getLang() {
		return lang;
	}

	/**
	 * Gets the value of the terms property.
	 *
	 * @return
	 *     possible object is
	 *     {@link KAF.Terms }
	 *
	 */
	public KAF.Terms getTerms() {
		return terms;
	}

	/**
	 * Gets the value of the text property.
	 *
	 * @return
	 *     possible object is
	 *     {@link KAF.Text }
	 *
	 */
	public KAF.Text getText() {
		return text;
	}

	/**
	 * Gets the value of the version property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * Sets the value of the kafHeader property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link KAF.KafHeader }
	 *
	 */
	public void setKafHeader(KAF.KafHeader value) {
		this.kafHeader = value;
	}

	/**
	 * Sets the value of the lang property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setLang(String value) {
		this.lang = value;
	}


	/**
	 * Sets the value of the terms property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link KAF.Terms }
	 *
	 */
	public void setTerms(KAF.Terms value) {
		this.terms = value;
	}


	/**
	 * Sets the value of the text property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link KAF.Text }
	 *
	 */
	public void setText(KAF.Text value) {
		this.text = value;
	}


	/**
	 * Sets the value of the version property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setVersion(String value) {
		this.version = value;
	}

}
